version: '3.8'

services:
  db-mysql:
    image: mysql:8
    volumes:
      - ../src/main/scripts/mysql:/docker-entrypoint-initdb.d      
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      

